### ISSUE TITLE
bqplot module has no attribute ScatterGL

### ISSUE THREAD

**Issue by havok2063** [glue-viz/glue-jupyter#53]
I'm trying to get glupyter installed and run some example code from your notebooks but am running into some issues.  I ran `pip install -e .` from within the glue-jupyter repo.  I installed the dev version of `ipyastroimage`.  (`pip install` failed).  When I try to create a 2d scatter plot, I'm getting 

`AttributeError: module 'bqplot' has no attribute 'ScatterGL'`

`glue-jupyter` installed bqplot version 0.11.2.  I can't find any reference to `ScatterGL` in any docs or references for `bqplot`.  Is there a custom version of `bqplot` I should have installed?  

Here is my code, which loads a small catalog as a table, and as test, tries to create an RA, Dec 2d scatter plot:

```
import glue_jupyter as gj
from glue.core.component_link import ComponentLink
from glue.core.data_factories import load_data
from glue import core as gcore
from astropy.io import fits
from astropy.table import Table
tic = Table.read('/Users/Brian/Dropbox/tess_work/data/catalog_66_-67.fits')
tic_data = gcore.Data('TIC', **tic)
app = gj.jglue(tic_data)
app.scatter2d('ra', 'dec')
```

**Comment by maartenbreddels** [comment]
Hi Brian,

yes, it needs a special branch of bqplot that is not yet merged:
```
$ pip install https://github.com/maartenbreddels/bqplot/archive/scatter_webgl.zip
```
Let me know if that works.

cheers,

Maarten

**Comment by havok2063** [comment]
Hi @maartenbreddels, 

I tried it and get the following error.  I have node and npm installed.  I'm using node `10.4.1` and npm `6.4.1`. 

```
pip install https://github.com/maartenbreddels/bqplot/archive/scatter_webgl.zip
Collecting https://github.com/maartenbreddels/bqplot/archive/scatter_webgl.zip
  Downloading https://github.com/maartenbreddels/bqplot/archive/scatter_webgl.zip
     - 6.1MB 4.3MB/s
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/Users/Brian/anaconda2/envs/py3.6/bin:/usr/local/opt/libarchive/bin:/usr/local/opt/qt/bin:/opt/local/bin:/opt/local/sbin:/Users/Brian/anaconda2/bin:/Users/Brian/Work/github_projects/havok2063/mimir/bin:/Users/Brian/Work/github_projects/Marvin/bin:/Users/Brian/Work/github_projects/marvin_brain/bin:/Users/Brian/Work/sdss/repo/manga/mangadrp/trunk/bin:/uufs/chpc.utah.edu/common/home/sdss01/software/eboss/NULL/photolog/dr10/bin:/Users/Brian/Work/sdss/data/sdss/catalogs/dust/trunk/bin:/Users/Brian/Work/sdss/repo/sdss/idlutils/trunk/bin:/Users/Brian/Work/sdss/data/manga/mangapreim/trunk/bin:/Users/Brian/Work/sdss/repo/manga/mangacore/trunk/bin:/Users/Brian/Work/sdss/data/sdss/speclog/trunk/bin:/Users/Brian/Work/github_projects/stui/bin:/Users/Brian/Work/sdss/repo/operations/apo/plc/trunk/bin:/Users/Brian/Work/github_projects/apo/hartmannActor/bin:/Users/Brian/Work/github_projects/apo/tron/bin:/Users/Brian/Work/github_projects/apo/guiderActor/bin:/Users/Brian/Work/sdss/repo/operations/general/PyGuide/2.2.1/bin:/Users/Brian/Work/github_projects/apo/sopActor/bin:/Users/Brian/Work/github_projects/apo/platedbActor/bin:/Users/Brian/Work/github_projects/apo/actorcore/bin:/Users/Brian/Work/github_projects/apo/opscore/bin:/Users/Brian/Work/github_projects/apo/actorkeys/bin:/Users/Brian/Work/sdss/repo/operations/general/RO/3.6.9/bin:/Users/Brian/Work/sdss/repo/sdss/sdss_python_module/marvin/bin:/Users/Brian/Work/sdss/repo/sdss/sdss4tools/0.2.6/bin:/Users/Brian/Work/sdss/repo/sdss/webapps/inspection/trunk/bin:/Users/Brian/Work/github_projects/sdss/cthreepo/bin:/Users/Brian/Work/github_projects/sdss/sdssdb/bin:/Users/Brian/Work/sdss/repo/sdss/datamodel/dr15/bin:/Users/Brian/Work/github_projects/sdss/tree/bin:/Users/Brian/Work/github_projects/sdss/sdss_access/bin:/opt/local/lib/postgresql96/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin:/Users/Brian/test/hellomarvin/bin:/Users/Brian/Work/github_projects/sdss/flipper/bin:/Users/Brian/Work/idl/kcorrect/bin:/Users/Brian/Work/Boss/platedesign/trunk/bin:+/Users/Brian/Work/github_projects/google_models/syntaxnet/bazel-bin/syntaxnet:+/usr/local/bin/jshint
    running egg_info
    running jsdeps
    6.4.1
    6.4.1
    Installing build dependencies with npm.  This may take a while...
    npm ERR! cb() never called!

    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://npm.community>
    rebuilding js and css failed
    missing files: ['/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/bqplot/static/extension.js', '/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/bqplot/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/setup.py", line 219, in <module>
        setup(**setup_args)
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/setup.py", line 88, in run
        raise e
      File "/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/setup.py", line 81, in run
        self.distribution.run_command('jsdeps')
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/setup.py", line 148, in run
        check_call(['npm', 'install'], cwd=node_root, stdout=sys.stdout, stderr=sys.stderr, shell=shell)
      File "/Users/Brian/anaconda2/envs/py3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j6/g80fb5pn2_j41jckdc4hyd5m0000gn/T/pip-req-build-jub6a5pw/ 
```

**Comment by maartenbreddels** [comment]
Could you try node 9 (easiest to install from conda-forge)?

(from mobile phone)

**Comment by YK-NY** [comment]
> Hi Brian,
> 
> yes, it needs a special branch of bqplot that is not yet merged:
> 
> ```
> $ pip install https://github.com/maartenbreddels/bqplot/archive/scatter_webgl.zip
> ```
> 
> Let me know if that works.
> 
> cheers,
> 
> Maarten

Hi Maarten -

I installed the latest version of bqplot (0.11.8) and I am learning to use bqplot. I get an error when I execute a piece of code in the ScatterMega.ipynb files - that is part of the bqplot example files. 
It says:
module 'bqplot' has no attribute'ScatterGL'. 
I get an error trying to install the files in the zip files you mentioned in one of the comments. I also cannot find any reference to ScatterGL in the documentation and on bqplot channel on gitter.

Can you please tell me how I can fix this?

Thank you.
