### ISSUE TITLE
npm installed buy pip saying it's not there

### ISSUE THREAD

**Issue by SaOgaz** [glue-viz/glue-jupyter#67]
Hi @astrofrog,  @ibusko and I both ran into this same problem.  We installed npm but the pip install claims it's not there.  Looking at the error message i'm wondering if this is a permissions problem?  We don't have admin permissions on our ST machines.  Here's the error, version of npm I have installed is 0.1.1

```
(pyinsky) moka:glue-jupyter ogaz$ pip install -e .
Obtaining file:///Users/ogaz/glue-jupyter
Collecting glue-core (from glue-jupyter==0.0.0)
  Using cached https://files.pythonhosted.org/packages/5b/02/dbcf55e0354099bdcbadd0b22d20157af7b51c266a47cb9fa63361e532ac/glue_core-0.14.2-py2.py3-none-any.whl
Collecting glue-vispy-viewers (from glue-jupyter==0.0.0)
  Using cached https://files.pythonhosted.org/packages/e8/26/7f4c0485dd831b285f09155a75e3e5489ead1c2253a4e9b6936acd51df2c/glue_vispy_viewers-0.11-py2.py3-none-any.whl
Requirement already satisfied: notebook in /Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/site-packages (from glue-jupyter==0.0.0) (5.7.8)
Collecting ipympl (from glue-jupyter==0.0.0)
  Using cached https://files.pythonhosted.org/packages/f3/95/0f81671c9b71ef50e39508e85395f8987734d1211833ec349509e7a78356/ipympl-0.2.1-py2.py3-none-any.whl
Collecting ipyvolume (from glue-jupyter==0.0.0)
  Using cached https://files.pythonhosted.org/packages/6c/e4/4a6754d2c390ee627f82aeaae76b34a1daf30eea80af41215eebedb0f5ce/ipyvolume-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: ipywidgets@ git+https://github.com/jupyter-widgets/ipywidgets.git#egg=ipywidgets from git+https://github.com/jupyter-widgets/ipywidgets.git#egg=ipywidgets in /Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/site-packages (from glue-jupyter==0.0.0) (7.4.2)
Collecting bqplot@ git+https://github.com/maartenbreddels/bqplot@scatter_webgl#egg=bqplot from git+https://github.com/maartenbreddels/bqplot@scatter_webgl#egg=bqplot (from glue-jupyter==0.0.0)
  Cloning https://github.com/maartenbreddels/bqplot (to revision scatter_webgl) to /private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot
Branch 'scatter_webgl' set up to track remote branch 'scatter_webgl' from 'origin'.
Switched to a new branch 'scatter_webgl'
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/Users/ogaz/miniconda3/envs/pyinsky/bin:/Users/ogaz/jfrog:/Users/ogaz/gcc/installation:/usr/local/mysql/bin:/Users/ogaz/miniconda3/bin:/sw/lib/perl5/ExtUtils:/sw/bin:/sw/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin
    running egg_info
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    rebuilding js and css failed
    missing files: ['/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/bqplot/static/extension.js', '/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/bqplot/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/setup.py", line 219, in <module>
        setup(**setup_args)
      File "/Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/setup.py", line 88, in run
        raise e
      File "/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/setup.py", line 81, in run
        self.distribution.run_command('jsdeps')
      File "/Users/ogaz/miniconda3/envs/pyinsky/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/setup.py", line 156, in run
        raise ValueError(msg)
    ValueError: Missing file: /private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/bqplot/static/extension.js
    npm is required to build a development version of widgetsnbextension
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w_/t1dtpm391bq6vyvhf6_lmn4m0003cg/T/pip-install-x7amirvz/bqplot/
```

**Comment by SaOgaz** [comment]
Looks like that might be the problem... https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/

**Comment by SaOgaz** [comment]
Okay, fixed by "conda install nodejs", closing this

**Comment by maartenbreddels** [comment]
I can recommend to install nodejs from conda:
```
conda install -c conda-forge nodejs
```

**Comment by maartenbreddels** [comment]
you beat me by 2 seconds :)
